//======================================================================================== 
// AthenaK: astrophysical fluid dynamics & numerical relativity code 
// Copyright(C) 2020 James M. Stone <jmstone@ias.edu> and the Athena code team 
// Licensed under the 3-clause BSD License 
//======================================================================================== 
//! \file z4c_id_solve.cpp 
//  \brief Problem generator for loading in initial data generated by id_solve 

#include <algorithm> 
#include <array> 
#include <cmath> 
#include <cstdlib> 
#include <iostream> 
#include <iterator>  
#include <sstream> 
#include <stdexcept> 
#include <string> 
#include <vector> 
#include <Kokkos_Timer.hpp> 

#include "athena.hpp" 
#include "coordinates/cell_locations.hpp" 
#include "coordinates/adm.hpp" 
#include "globals.hpp" 
#include "mesh/mesh.hpp" 
#include "parameter_input.hpp" 
#include "z4c/z4c.hpp" 
#include "z4c/z4c_amr.hpp" 

#include <hdf5.h> 

// Forward declarations for interpolator 
static double lagrange1D(const double *x, const double *f, double xp); 
static double interpolate_3d_cmajor( 
    const double *x, int nx, 
    const double *y, int ny, 
    const double *z, int nz, 
    const double *f, 
    double xp, double yp, double zp 
); 

//----------------------------------------------------------------------------- 
// Read a full dataset of doubles from an HDF5 file. 
void read_hdf5(const char *filename, double **data, hsize_t *dims, const char *DATASET_NAME) { 
    hid_t  file_id, dataset_id, dataspace_id; 
    herr_t status; 

    file_id = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT); 
    if (file_id < 0) { 
        throw std::runtime_error("Error opening file: " + std::string(filename)); 
    } 

    dataset_id = H5Dopen2(file_id, DATASET_NAME, H5P_DEFAULT); 
    if (dataset_id < 0) { 
        H5Fclose(file_id); 
        throw std::runtime_error("Error opening dataset: " + std::string(DATASET_NAME)); 
    } 

    dataspace_id = H5Dget_space(dataset_id); 
    H5Sget_simple_extent_dims(dataspace_id, dims, NULL); 

    int rank = H5Sget_simple_extent_ndims(dataspace_id); 
    hsize_t total_size = 1; 
    for (int d = 0; d < rank; ++d) total_size *= dims[d]; 

    try { 
        *data = new double[total_size]; 
    } catch (const std::bad_alloc& e) { 
        H5Sclose(dataspace_id); 
        H5Dclose(dataset_id); 
        H5Fclose(file_id); 
        throw std::runtime_error("Memory allocation failed for dataset " + std::string(DATASET_NAME)); 
    } 

    status = H5Dread(dataset_id, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, *data); 
    if (status < 0) { 
        delete[] *data; 
        *data = nullptr; 
        H5Sclose(dataspace_id); 
        H5Dclose(dataset_id); 
        H5Fclose(file_id); 
        throw std::runtime_error("Error reading dataset " + std::string(DATASET_NAME)); 
    } 

    H5Sclose(dataspace_id); 
    H5Dclose(dataset_id); 
    H5Fclose(file_id); 
} 

void LoadIDSolveData(MeshBlockPack *pmbp, ParameterInput *pin, const std::string &file_name); 
void RefinementCondition(MeshBlockPack *pmbp); 

//---------------------------------------------------------------------------------------- 
//! \fn ProblemGenerator::UserProblem_() 
void ProblemGenerator::UserProblem(ParameterInput *pin, const bool restart) { 
    user_ref_func = RefinementCondition; 
    if (restart) return; 

    MeshBlockPack *pmbp = pmy_mesh_->pmb_pack; 
    auto &indcs = pmy_mesh_->mb_indcs; 

    std::cout << "Start Loading id_solve Initial Data: " 
              << pin->GetOrAddString("problem", "id_filename", "EMPTY") << std::endl; 
    try { 
        LoadIDSolveData(pmbp, pin, pin->GetOrAddString("problem", "id_filename", "EMPTY")); 
    } catch (const std::exception& e) { 
        std::cerr << "### FATAL ERROR in ProblemGenerator ###" << std::endl; 
        std::cerr << e.what() << std::endl; 
        exit(EXIT_FAILURE); 
    } 

    switch (indcs.ng) { 
      case 2: pmbp->pz4c->ADMToZ4c<2>(pmbp, pin); break; 
      case 3: pmbp->pz4c->ADMToZ4c<3>(pmbp, pin); break; 
      case 4: pmbp->pz4c->ADMToZ4c<4>(pmbp, pin); break; 
    } 
    pmbp->pz4c->Z4cToADM(pmbp); 
    pmbp->pz4c->GaugePreCollapsedLapse(pmbp, pin); 

    switch (indcs.ng) { 
      case 2: pmbp->pz4c->ADMConstraints<2>(pmbp); break; 
      case 3: pmbp->pz4c->ADMConstraints<3>(pmbp); break; 
      case 4: pmbp->pz4c->ADMConstraints<4>(pmbp); break; 
    } 

    std::cout << "Loading initial data complete." << std::endl; 
} 

//----------------------------------------------------------------------------- 
void LoadIDSolveData(MeshBlockPack *pmbp, ParameterInput *pin, const std::string &file_name) { 
  double *data_x1v=nullptr, *data_x2v=nullptr, *data_x3v=nullptr; 
  hsize_t dims_x[2], dims_y[2], dims_z[2]; 
  read_hdf5(file_name.c_str(), &data_x1v, dims_x, "x1v"); 
  read_hdf5(file_name.c_str(), &data_x2v, dims_y, "x2v"); 
  read_hdf5(file_name.c_str(), &data_x3v, dims_z, "x3v"); 

  int number_of_meshblocks = static_cast<int>(dims_x[0]); 
  int meshblock_dimx = static_cast<int>(dims_x[1]); 
  int meshblock_dimy = static_cast<int>(dims_y[1]); 
  int meshblock_dimz = static_cast<int>(dims_z[1]); 

  double *metric_data=nullptr, *extrin_data=nullptr; 
  hsize_t dims_m[5], dims_e[5]; 
  read_hdf5(file_name.c_str(), &metric_data, dims_m, "metric"); 
  read_hdf5(file_name.c_str(), &extrin_data, dims_e, "extrin"); 

  int nblocks = static_cast<int>(dims_m[1]); 
  int NX = static_cast<int>(dims_m[2]); 
  int NY = static_cast<int>(dims_m[3]); 
  int NZ = static_cast<int>(dims_m[4]); 

  // FIX: Consistency Checks
  if (meshblock_dimx != NX || meshblock_dimy != NY || meshblock_dimz != NZ) {
      throw std::runtime_error("HDF5 dimension mismatch between coordinates and metric/extrin.");
  }
  if (number_of_meshblocks != nblocks) {
      throw std::runtime_error("HDF5 block-count mismatch.");
  }

  int block_vol = NX*NY*NZ; 
  int comp_stride = nblocks * block_vol; 

  auto &u_adm = pmbp->padm->u_adm; 
  auto host_u_adm = create_mirror(u_adm); 
  z4c::Z4c::ADMhost_vars host_adm; 
  host_adm.psi4.InitWithShallowSlice(host_u_adm, adm::ADM::I_ADM_PSI4); 
  host_adm.g_dd.InitWithShallowSlice(host_u_adm, adm::ADM::I_ADM_GXX, adm::ADM::I_ADM_GZZ); 
  host_adm.vK_dd.InitWithShallowSlice(host_u_adm, adm::ADM::I_ADM_KXX, adm::ADM::I_ADM_KZZ); 

  auto &indcs = pmbp->pmesh->mb_indcs; 
  auto &size = pmbp->pmb->mb_size;   

  int is = indcs.is; int ie = indcs.ie; 
  int js = indcs.js; int je = indcs.je; 
  int ks = indcs.ks; int ke = indcs.ke; 
  int isg = is-indcs.ng; int ieg = ie+indcs.ng; 
  int jsg = js-indcs.ng; int jeg = je+indcs.ng; 
  int ksg = ks-indcs.ng; int keg = ke+indcs.ng; 
  int nmb = pmbp->nmb_thispack; 

  Real r_fill = pin->GetOrAddReal("z4c", "r_fill", 0.5); 
  const bool apply_puncture_fill = (r_fill > 0.0); 
  Real c0_x = pin->GetOrAddReal("z4c", "co_0_x", 0.0), c0_y = pin->GetOrAddReal("z4c", "co_0_y", 0.0), c0_z = pin->GetOrAddReal("z4c", "co_0_z", 0.0); 
  Real M_0 = pin->GetOrAddReal("z4c", "M_fill_0", 0.5); 
  Real c1_x = pin->GetOrAddReal("z4c", "co_1_x", 0.0), c1_y = pin->GetOrAddReal("z4c", "co_1_y", 0.0), c1_z = pin->GetOrAddReal("z4c", "co_1_z", 0.0); 
  Real M_1 = pin->GetOrAddReal("z4c", "M_fill_1", 0.5); 

  // Cache variables
  int last_meshblock = -1; 
  std::vector<double> xd(NX), yd(NY), zd(NZ); 
  double xmin_a, xmax_a, ymin_a, ymax_a, zmin_a, zmax_a; 

  for (int m = 0; m < nmb; ++m) { 
    // FIX: Reset cache per destination meshblock
    last_meshblock = -1;

    for (int kk = ksg; kk <= keg; ++kk) { 
    for (int jj = jsg; jj <= jeg; ++jj) { 
    for (int ii = isg; ii <= ieg; ++ii) { 
        
      Real xx = CellCenterX(ii-is, indcs.nx1, size.h_view(m).x1min, size.h_view(m).x1max); 
      Real yy = CellCenterX(jj-js, indcs.nx2, size.h_view(m).x2min, size.h_view(m).x2max); 
      Real zz = CellCenterX(kk-ks, indcs.nx3, size.h_view(m).x3min, size.h_view(m).x3max); 

      // FIX: Reuse check against ACTIVE bounds only
      if (last_meshblock == -1 || 
          xx <= xmin_a || xx > xmax_a || 
          yy <= ymin_a || yy > ymax_a || 
          zz <= zmin_a || zz > zmax_a) { 

        int meshblock = -1; 
        int ng_src = indcs.ng; 

        for (int pass = 0; pass < 2; ++pass) {
            for (int l = 0; l < number_of_meshblocks; ++l) { 
                // Guard dimension access
                if (meshblock_dimx < 2 || meshblock_dimy < 2 || meshblock_dimz < 2) {
                    throw std::runtime_error("Source coordinate block dimension < 2");
                }
                double dx = data_x1v[l*meshblock_dimx + 1] - data_x1v[l*meshblock_dimx + 0]; 
                double dy = data_x2v[l*meshblock_dimy + 1] - data_x2v[l*meshblock_dimy + 0]; 
                double dz = data_x3v[l*meshblock_dimz + 1] - data_x3v[l*meshblock_dimz + 0]; 

                double xmin_l = data_x1v[l*meshblock_dimx+0]-dx/2.0; 
                double xmax_l = data_x1v[l*meshblock_dimx + meshblock_dimx-1]+dx/2.0; 
                double ymin_l = data_x2v[l*meshblock_dimy+0]-dy/2.0; 
                double ymax_l = data_x2v[l*meshblock_dimy + meshblock_dimy-1]+dy/2.0; 
                double zmin_l = data_x3v[l*meshblock_dimz+0]-dz/2.0; 
                double zmax_l = data_x3v[l*meshblock_dimz + meshblock_dimz-1]+dz/2.0; 

                double s_xmin = xmin_l, s_xmax = xmax_l;
                double s_ymin = ymin_l, s_ymax = ymax_l;
                double s_zmin = zmin_l, s_zmax = zmax_l;

                if (pass == 0) { // Shrink to active region
                    s_xmin += ng_src * dx; s_xmax -= ng_src * dx;
                    s_ymin += ng_src * dy; s_ymax -= ng_src * dy;
                    s_zmin += ng_src * dz; s_zmax -= ng_src * dz;
                }

                if (xx > s_xmin && xx <= s_xmax && yy > s_ymin && yy <= s_ymax && zz > s_zmin && zz <= s_zmax) { 
                    meshblock = l; 
                    xmin_a = xmin_l + ng_src * dx; xmax_a = xmax_l - ng_src * dx;
                    ymin_a = ymin_l + ng_src * dy; ymax_a = ymax_l - ng_src * dy;
                    zmin_a = zmin_l + ng_src * dz; zmax_a = zmax_l - ng_src * dz;
                    break; 
                } 
            }
            if (meshblock != -1) break;
        }

        if (meshblock == -1) { 
            if (!(ii<is || ii>ie || jj<js || jj>je || kk<ks || kk>ke)) { 
              std::stringstream msg; msg << "Active cell (" << xx << "," << yy << "," << zz << ") not found."; 
              throw std::runtime_error(msg.str()); 
            } 
            last_meshblock = -1; continue; 
        } 

        if (meshblock != last_meshblock) { 
          for (int i=0; i<NX; ++i) xd[i] = data_x1v[meshblock*meshblock_dimx + i]; 
          for (int j=0; j<NY; ++j) yd[j] = data_x2v[meshblock*meshblock_dimy + j]; 
          for (int k=0; k<NZ; ++k) zd[k] = data_x3v[meshblock*meshblock_dimz + k]; 
          last_meshblock = meshblock; 
        } 
      } 
        
      if (last_meshblock < 0 || last_meshblock >= nblocks) continue; 

      const double *xd_ptr=xd.data(), *yd_ptr=yd.data(), *zd_ptr=zd.data(); 
      const double *metric_ptr = metric_data + (last_meshblock * block_vol); 
      const double *extrin_ptr = extrin_data + (last_meshblock * block_vol); 

      host_adm.g_dd(m,0,0,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 0*comp_stride, xx,yy,zz); 
      host_adm.g_dd(m,0,1,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 1*comp_stride, xx,yy,zz); 
      host_adm.g_dd(m,0,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 2*comp_stride, xx,yy,zz); 
      host_adm.g_dd(m,1,1,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 3*comp_stride, xx,yy,zz); 
      host_adm.g_dd(m,1,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 4*comp_stride, xx,yy,zz); 
      host_adm.g_dd(m,2,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, metric_ptr + 5*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,0,0,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 0*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,0,1,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 1*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,0,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 2*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,1,1,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 3*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,1,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 4*comp_stride, xx,yy,zz); 
      host_adm.vK_dd(m,2,2,kk,jj,ii) = interpolate_3d_cmajor(xd_ptr,NX,yd_ptr,NY,zd_ptr,NZ, extrin_ptr + 5*comp_stride, xx,yy,zz); 
   
      if (apply_puncture_fill) {
          const Real eps = 1.0e-12; 
          Real r0 = std::sqrt(SQR(xx - c0_x) + SQR(yy - c0_y) + SQR(zz - c0_z)) + eps;
          Real r1 = std::sqrt(SQR(xx - c1_x) + SQR(yy - c1_y) + SQR(zz - c1_z)) + eps;
          Real r = std::min(r0, r1); 

          if (r < r_fill) {
              Real x_f = r / r_fill;
              Real f = 1.0 - x_f*x_f*x_f * (10.0 - 15.0*x_f + 6.0*x_f*x_f); 
              Real psi_p = 1.0 + M_0 / (2.0 * r0) + M_1 / (2.0 * r1);
              Real psi4_p = SQR(SQR(psi_p));

              host_adm.g_dd(m,0,0,kk,jj,ii) = f * psi4_p + (1.0 - f) * host_adm.g_dd(m,0,0,kk,jj,ii);
              host_adm.g_dd(m,0,1,kk,jj,ii) *= (1.0 - f);
              host_adm.g_dd(m,0,2,kk,jj,ii) *= (1.0 - f);
              host_adm.g_dd(m,1,1,kk,jj,ii) = f * psi4_p + (1.0 - f) * host_adm.g_dd(m,1,1,kk,jj,ii);
              host_adm.g_dd(m,1,2,kk,jj,ii) *= (1.0 - f);
              host_adm.g_dd(m,2,2,kk,jj,ii) = f * psi4_p + (1.0 - f) * host_adm.g_dd(m,2,2,kk,jj,ii);

              for(int i_k=0; i_k<3; ++i_k) for(int j_k=i_k; j_k<3; ++j_k) host_adm.vK_dd(m,i_k,j_k,kk,jj,ii) *= (1.0 - f);
          }
      }
    }}} 
  } 

  delete[] data_x1v; delete[] data_x2v; delete[] data_x3v; 
  delete[] metric_data; delete[] extrin_data; 
  Kokkos::deep_copy(u_adm, host_u_adm); 
} 

void RefinementCondition(MeshBlockPack *pmbp) { pmbp->pz4c->pamr->Refine(pmbp); } 

static double lagrange1D(const double *x, const double *f, double xp) { 
    double result = 0.0; 
    for (int i = 0; i < 5; i++) { 
        double term = f[i]; 
        for (int j = 0; j < 5; j++) { if (j != i) term *= (xp - x[j]) / (x[i] - x[j]); } 
        result += term; 
    } 
    return result; 
} 

static double interpolate_3d_cmajor(const double *x, int nx, const double *y, int ny, const double *z, int nz, const double *f, double xp, double yp, double zp) { 
    // FIX: Hard guard for stencil size
    if (nx < 5 || ny < 5 || nz < 5) throw std::runtime_error("interpolate_3d_cmajor requires nx,ny,nz >= 5");

    if (xp < x[0]) xp = x[0]; else if (xp > x[nx-1]) xp = x[nx-1]; 
    if (yp < y[0]) yp = y[0]; else if (yp > y[ny-1]) yp = y[ny-1]; 
    if (zp < z[0]) zp = z[0]; else if (zp > z[nz-1]) zp = z[nz-1]; 

    auto find_closest_index = [](const double *arr, int n, double val) { 
        const double *it = std::lower_bound(arr, arr + n, val); 
        int idx = std::distance(arr, it); 
        if (idx == n) idx = n - 1; 
        else if (idx > 0 && std::fabs(val - arr[idx - 1]) < std::fabs(val - arr[idx])) idx--; 
        return idx; 
    }; 

    int ix = find_closest_index(x, nx, xp), iy = find_closest_index(y, ny, yp), iz = find_closest_index(z, nz, zp); 
    int sx = std::max(0, std::min(ix - 2, nx - 5)); 
    int sy = std::max(0, std::min(iy - 2, ny - 5)); 
    int sz = std::max(0, std::min(iz - 2, nz - 5)); 

    double x5[5], y5[5], z5[5]; 
    for (int i = 0; i < 5; i++) { x5[i] = x[sx + i]; y5[i] = y[sy + i]; z5[i] = z[sz + i]; } 

    double yz_interp[5][5]; 
    for (int i = 0; i < 5; i++) { 
        for (int j = 0; j < 5; j++) { 
            double fz[5]; 
            for (int k = 0; k < 5; k++) fz[k] = f[(sz + k) * ny * nx + (sy + j) * nx + (sx + i)]; 
            yz_interp[i][j] = lagrange1D(z5, fz, zp); 
        } 
    } 

    double x_interp[5]; 
    for (int i = 0; i < 5; i++) { 
        double fy[5]; 
        for (int j = 0; j < 5; j++) fy[j] = yz_interp[i][j]; 
        x_interp[i] = lagrange1D(y5, fy, yp); 
    } 
    return lagrange1D(x5, x_interp, xp); 
}