#!/usr/bin/env python3
"""Run AthenaK id_solve imports for a SpECK critical-collapse HDF5 sequence.

The script converts uniform SpECK ADM Cartesian dumps into the id_solve HDF5
layout, runs the custom ``z4c_id_solve`` problem, and prints the imported
constraint RMS values and resolution-to-resolution ratios.

Example:
  python3 scripts/z4c/run_id_solve_collapse_convergence.py \\
    --athena-bin build-id-solve/src/athena \\
    --source-pattern '../SpECK/build/gw_collapse_practical_20260515/cart_hdf5/gw_collapse_L12.adm_N{N}_ng{ng}.00000.h5' \\
    --out /tmp/id_solve_collapse --resolutions 16,32,64 --ghosts 2
"""

from __future__ import annotations

import argparse
import math
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[2]
CONVERTER_SOURCE = REPO_ROOT / "scripts/z4c/convert_speck_adm_cart_to_id_solve.cpp"


def parse_csv_ints(text: str) -> list[int]:
    values = []
    for piece in text.split(","):
        piece = piece.strip()
        if piece:
            values.append(int(piece))
    return values


def h5dump_values(path: Path, dataset: str) -> list[float]:
    output = subprocess.check_output(
        ["h5dump", "-d", dataset, str(path)], text=True
    )
    try:
        data_text = output.split("DATA {", 1)[1].split("}", 1)[0]
    except IndexError as exc:
        raise RuntimeError(f"could not parse h5dump output for {dataset}") from exc
    value_text = []
    for line in data_text.splitlines():
        if ":" in line:
            value_text.append(line.split(":", 1)[1])
        else:
            value_text.append(line)
    return [
        float(x)
        for x in re.findall(
            r"[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?",
            "\n".join(value_text),
        )
    ]


def compile_converter(out_dir: Path) -> Path:
    converter = out_dir / "convert_speck_adm_cart_to_id_solve"
    needs_build = not converter.exists()
    if converter.exists():
        needs_build = converter.stat().st_mtime < CONVERTER_SOURCE.stat().st_mtime
    if needs_build:
        subprocess.run(
            [
                "h5c++",
                "-std=c++17",
                "-O2",
                str(CONVERTER_SOURCE),
                "-o",
                str(converter),
            ],
            check=True,
        )
    return converter


def write_input(
    path: Path,
    basename: str,
    id_filename: Path,
    n: int,
    nghost: int,
    half_width: float,
    meshblock: int,
) -> None:
    path.write_text(
        f"""# Auto-generated by scripts/z4c/run_id_solve_collapse_convergence.py.

<comment>
problem   = critical-collapse id_solve import convergence

<job>
basename  = {basename}

<mesh>
nghost    = {nghost}
nx1       = {n}
x1min     = {-half_width:.17g}
x1max     = {half_width:.17g}
ix1_bc    = outflow
ox1_bc    = outflow

nx2       = {n}
x2min     = {-half_width:.17g}
x2max     = {half_width:.17g}
ix2_bc    = outflow
ox2_bc    = outflow

nx3       = {n}
x3min     = {-half_width:.17g}
x3max     = {half_width:.17g}
ix3_bc    = outflow
ox3_bc    = outflow

<meshblock>
nx1       = {meshblock}
nx2       = {meshblock}
nx3       = {meshblock}

<time>
evolution  = dynamic
integrator = rk4
cfl_number = 0.3
nlim       = 0
tlim       = 0.0
ndiag      = 1

<z4c>
diss       = 0.0
excise_chi = 0.0

<problem>
pgen_name = z4c_id_solve
id_filename = {id_filename}
write_constraint_summary = true
fail_if_c_rms_above = 1.0e300
fail_if_h_rms_above = 1.0e300
fail_if_m_rms_above = 1.0e300
fail_if_z_rms_above = 1.0e300

<output1>
file_type   = hst
data_format = %24.16e
dt          = -1.0
""",
        encoding="utf-8",
    )


def read_summary(path: Path) -> dict[str, float]:
    lines = [line for line in path.read_text(encoding="utf-8").splitlines() if line and not line.startswith("#")]
    if not lines:
        raise RuntimeError(f"empty constraint summary: {path}")
    fields = lines[-1].split()
    return {
        "N": float(fields[0]),
        "C": float(fields[4]),
        "H": float(fields[5]),
        "M": float(fields[6]),
        "Z": float(fields[7]),
        "Volume": float(fields[8]),
    }


def observed_order(prev: float, current: float, refinement: float = 2.0) -> float:
    if prev <= 0.0 or current <= 0.0:
        return float("nan")
    return math.log(prev / current) / math.log(refinement)


def run_suite(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    converter = compile_converter(out_dir)
    athena = Path(args.athena_bin).resolve()
    if not athena.exists():
        raise RuntimeError(f"athena binary does not exist: {athena}")

    rows: list[tuple[int, int, dict[str, float]]] = []
    for nghost in args.ghosts:
        for n in args.resolutions:
            source = Path(args.source_pattern.format(N=n, ng=nghost)).resolve()
            if not source.exists():
                raise RuntimeError(f"source HDF5 does not exist: {source}")
            npts = [int(x) for x in h5dump_values(source, "numpoints")]
            center = h5dump_values(source, "center")
            extent = h5dump_values(source, "extent")
            if any(abs(c) > 1.0e-12 for c in center):
                raise RuntimeError("this convergence runner currently expects centered data")
            if npts[0] != n + 2 * nghost:
                raise RuntimeError(
                    f"{source} has numpoints[0]={npts[0]}, expected N+2*ng={n + 2 * nghost}"
                )
            dx = 2.0 * extent[0] / float(npts[0] - 1)
            half_width = 0.5 * n * dx
            meshblock = args.meshblock if args.meshblock > 0 else n
            if n % meshblock != 0:
                raise RuntimeError(f"N={n} is not divisible by meshblock={meshblock}")

            run_dir = out_dir / f"N{n}_ng{nghost}_mb{meshblock}"
            run_dir.mkdir(parents=True, exist_ok=True)
            id_file = run_dir / f"critical_collapse_N{n}_ng{nghost}.id_solve.h5"
            subprocess.run([str(converter), str(source), str(id_file)], check=True)
            basename = f"idcollapse_N{n}_ng{nghost}_mb{meshblock}"
            input_file = run_dir / f"{basename}.athinput"
            write_input(input_file, basename, id_file, n, nghost, half_width, meshblock)
            subprocess.run([str(athena), "-i", str(input_file)], cwd=run_dir, check=True)
            summary = read_summary(run_dir / f"{basename}-id-solve-constraints.dat")
            rows.append((n, nghost, summary))

    print("# N  nghost  C_rms  H_rms  M_rms  Z_rms  pH(prev)  pM(prev)")
    previous_by_ng: dict[int, tuple[int, dict[str, float]]] = {}
    for n, nghost, summary in rows:
        p_h = float("nan")
        p_m = float("nan")
        if nghost in previous_by_ng:
            prev_n, prev = previous_by_ng[nghost]
            p_h = observed_order(prev["H"], summary["H"], n / prev_n)
            p_m = observed_order(prev["M"], summary["M"], n / prev_n)
        previous_by_ng[nghost] = (n, summary)
        print(
            f"{n:5d} {nghost:7d} "
            f"{summary['C']:.16e} {summary['H']:.16e} "
            f"{summary['M']:.16e} {summary['Z']:.16e} "
            f"{p_h:.6g} {p_m:.6g}"
        )
    return 0


def main(argv: Iterable[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--athena-bin", required=True, help="Path to z4c_id_solve AthenaK binary")
    parser.add_argument(
        "--source-pattern",
        required=True,
        help="SpECK ADM HDF5 pattern with {N} and {ng} placeholders",
    )
    parser.add_argument("--out", required=True, help="Output/work directory")
    parser.add_argument("--resolutions", default="16,32,64", type=parse_csv_ints)
    parser.add_argument("--ghosts", default="2,3,4", type=parse_csv_ints)
    parser.add_argument(
        "--meshblock",
        type=int,
        default=0,
        help="MeshBlock size; default uses a single MeshBlock per run",
    )
    args = parser.parse_args(list(argv))
    return run_suite(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
