#!/bin/bash
#SBATCH -A AST207
#SBATCH -o galaxy_%j.log
#SBATCH -t 04:59:59
#SBATCH -p batch  #extended
#SBATCH -q normal #debug #normal
#SBATCH -N 256

module restore
module load PrgEnv-cray
module load craype-accel-amd-gfx90a
module load cpe/25.09 cray-mpich/9.0.1 rocm/6.4.2
module load cce/20.0.0
module unload darshan-runtime

export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
export MPICH_ENV_DISPLAY=1
export MPICH_VERSION_DISPLAY=1
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED=1
export MPICH_OFI_NIC_POLICY=GPU
export MPICH_GPU_IPC_CACHE_MAX_SIZE=1000
export MPICH_MPIIO_HINTS="*:romio_cb_write=disable"
export MPICH_OFI_NUM_CQ_ENTRIES=131072
export FI_MR_CACHE_MONITOR=kdreg2
export FI_CXI_RX_MATCH_MODE=software
export HSA_XNACK=1

srun -N 256 -n 2048 -c 7 --gpus-per-node=8 --gpu-bind=closest \
        /ccs/home/zunyibrent/Work/athenak/build/src/athena \
        -i input -d data -t 04:55:00
