#!/usr/bin/env python3
"""Create a low-resolution sink-to-AMR dynbbh regression case."""

from __future__ import annotations

import json
import math
from pathlib import Path


ROOT = Path("/Users/hengrui/Desktop/research/gr/athenak")
CASE = ROOT / "analysis" / "dynbbh_zoom_sink"
RUN_LOW = Path("/tmp/dynbbh_zoom_sink_low")
RUN_ZOOM = Path("/tmp/dynbbh_zoom_sink_zoom")
TABLE = CASE / "tilted_spin_sep4_11orbit.dat"
LOW_INPUT = CASE / "tilted_spin_sep4_low_sink.athinput"
ZOOM_INPUT = CASE / "tilted_spin_sep4_zoom_restart.athinput"
NOTEBOOK = CASE / "dynbbh_zoom_sink_diagnostics.ipynb"
DIAG_SCRIPT = CASE / "run_zoom_sink_diagnostics.py"

SEP = 4.0
OMEGA = math.sqrt(1.0 / SEP**3)
TORBIT = 2.0 * math.pi / OMEGA
LOW_TLIM = 10.0 * TORBIT
ZOOM_TLIM = 11.0 * TORBIT


def unit_scaled(vec: tuple[float, float, float], mag: float) -> tuple[float, float, float]:
    norm = math.sqrt(sum(v * v for v in vec))
    return tuple(mag * v / norm for v in vec)


def write_table() -> None:
    chi1 = unit_scaled((0.31, -0.76, 0.57), 0.95)
    chi2 = unit_scaled((-0.73, 0.22, 0.65), 0.95)
    nrows = 2201
    r1 = 0.5 * SEP
    r2 = -0.5 * SEP
    with TABLE.open("w", encoding="utf-8") as f:
        f.write(
            "# Time M1 M2 x1 y1 z1 x2 y2 z2 chi_1_x chi_1_y chi_1_z "
            "chi_2_x chi_2_y chi_2_z vx1 vy1 vz1 vx2 vy2 vz2\n"
        )
        for n in range(nrows):
            t = ZOOM_TLIM * n / (nrows - 1)
            c = math.cos(OMEGA * t)
            s = math.sin(OMEGA * t)
            x1, y1, z1 = r1 * c, r1 * s, 0.0
            x2, y2, z2 = r2 * c, r2 * s, 0.0
            vx1, vy1, vz1 = -r1 * OMEGA * s, r1 * OMEGA * c, 0.0
            vx2, vy2, vz2 = -r2 * OMEGA * s, r2 * OMEGA * c, 0.0
            row = (
                t, 0.5, 0.5, x1, y1, z1, x2, y2, z2,
                *chi1, *chi2, vx1, vy1, vz1, vx2, vy2, vz2,
            )
            f.write(" ".join(f"{v:.16e}" for v in row) + "\n")


def common_input(mesh_refinement: str, num_levels: int, tlim: float,
                 out_dt: float, rst_dt: float,
                 require_resolved: str, refinement_region: str) -> str:
    return f"""<comment>
problem   = dynbbh unresolved-sink to AMR zoom test
reference = generated by analysis/dynbbh_zoom_sink/setup_zoom_sink_case.py

<job>
basename  = torus

<mesh>
nghost = 4
nx1    = 16
x1min  = -8.0
x1max  = 8.0
ix1_bc = outflow
ox1_bc = outflow

nx2    = 16
x2min  = -8.0
x2max  = 8.0
ix2_bc = outflow
ox2_bc = outflow

nx3    = 16
x3min  = -8.0
x3max  = 8.0
ix3_bc = outflow
ox3_bc = outflow

<meshblock>
nx1  = 4
nx2  = 4
nx3  = 4

<time>
evolution  = dynamic
integrator = rk2
cfl_number = 0.20
nlim       = -1
tlim       = {tlim:.16e}
ndiag      = 100

<mesh_refinement>
refinement       = {mesh_refinement}
max_nmb_per_rank = 500
num_levels       = {num_levels}
refinement_interval = 1
ncycle_check = 1
prolong_primitives = false

<amr_criterion0>
method = user

<coord>
general_rel = true
m           = 1.0
a           = 0.0
excise      = true
excision_scheme = puncture
smooth_excision = true
smooth_excision_width = 0.75
smooth_excision_inflow_speed = 0.40
smooth_excision_sigma_max = 1.0e5
smooth_excision_b_damping = true
smooth_excision_b_damping_eta = 0.5
smooth_excision_b_damping_cfl = 0.25
require_resolved_horizon = {require_resolved}
excise_lapse = 0.5
dexcise = 1.0e-10
pexcise = 1.0e-18

<mhd>
eos         = ideal
dyn_eos     = ideal
dyn_error   = reset_floor
reconstruct = plm
rsolver     = llf
dfloor      = 1.0e-10
pfloor      = 1.0e-18
tfloor      = 1.0e-8
gamma       = 1.44444444444
fofc        = true
gamma_max   = 20.0
enforce_maximum = true
dmp_M       = 1.2
calculate_tmunu = true

<adm>
dynamic = true

<problem>
chakrabarti_torus = true
r_edge            = 5.0
r_peak            = 10.0
tilt_angle        = 0.0
potential_beta_min = 100.0
potential_cutoff   = 0.2
potential_rho_pow = 1.0
rho_min   = 1.0e-5
rho_pow   = -1.5
pgas_min  = 0.333e-7
pgas_pow  = -2.5
rho_max   = 1.0
l         = 0.0
pert_amp  = 2.0e-2
user_hist = false
sep = {SEP:.16e}
q = 1.0
a1 = 0.95
a2 = 0.95
th_a1 = 55.0
ph_a1 = 292.0
th_a2 = 47.0
ph_a2 = 163.0
use_traj_table = true
traj_file = {TABLE}
unresolved_sink = true
sink_radius = 0.0
sink_width = -1.0
sink_cells_per_radius = 10.0
sink_resolved_cells_across_horizon = 20.0
sink_timescale = {5.0 * TORBIT:.16e}
sink_density_floor = 1.0e-6
sink_pressure_floor = 1.0e-8

amr_condition = none
radius_thr = 10.0
tracker_1_rad = 10.0
tracker_2_rad = 10.0
tracker_1_reflevel = -1
tracker_2_reflevel = -1
alpha_thr = 0.2
{refinement_region}

<output1>
file_type  = bin
variable   = mhd_w_bcc
dt         = {out_dt:.16e}

<output2>
file_type  = bin
variable   = mhd_divb
dt         = {out_dt:.16e}

<output3>
file_type  = rst
dt         = {rst_dt:.16e}
"""


def write_inputs() -> None:
    LOW_INPUT.write_text(
        common_input(
            mesh_refinement="none",
            num_levels=1,
            tlim=LOW_TLIM,
            out_dt=2.0 * TORBIT,
            rst_dt=LOW_TLIM,
            require_resolved="false",
            refinement_region="radius_0_rad = 24.0\nradius_0_reflevel = 0",
        ),
        encoding="utf-8",
    )
    ZOOM_INPUT.write_text(
        common_input(
            mesh_refinement="adaptive",
            num_levels=2,
            tlim=ZOOM_TLIM,
            out_dt=0.25 * TORBIT,
            rst_dt=10.0 * TORBIT,
            require_resolved="false",
            refinement_region="radius_0_rad = 3.25\nradius_0_reflevel = 1",
        ),
        encoding="utf-8",
    )


def nb_cell(source: str, cell_type: str = "code") -> dict:
    cell = {"cell_type": cell_type, "metadata": {}, "source": source.splitlines(keepends=True)}
    if cell_type == "code":
        cell["outputs"] = []
        cell["execution_count"] = None
    return cell


def diagnostics_source() -> str:
    return f"""from pathlib import Path
import math
import sys
import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, '{ROOT / "scripts"}')
from plot_tov_ks_binary_slices import read_binary_slice

case_dir = Path('{CASE}')
runs = [Path('{RUN_LOW}'), Path('{RUN_ZOOM}')]
labels = ['low_sink_10_orbits', 'zoom_amr_1_orbit']
table_path = Path('{TABLE}')
torbit = {TORBIT!r}
x3min, x3max = -8.0, 8.0

traj = np.loadtxt(table_path, comments='#')

def interp(col, t):
    return float(np.interp(t, traj[:,0], traj[:,col]))

def interp_vec(cols, t):
    return np.array([interp(c, t) for c in cols])

def z_centers_for(data):
    nz = next(iter(data.variables.values())).shape[0]
    dz = (x3max - x3min)/nz
    return x3min + (np.arange(nz) + 0.5)*dz

def kerr_radius(dx, dy, dz, avec):
    a2 = float(np.dot(avec, avec))
    rr = dx*dx + dy*dy + dz*dz
    if a2 <= 0.0:
        return np.sqrt(rr)
    ahat_dot_x = (avec[0]*dx + avec[1]*dy + avec[2]*dz)/math.sqrt(a2)
    term = rr - a2
    return np.sqrt(0.5*(term + np.sqrt(term*term + 4.0*a2*ahat_dot_x*ahat_dot_x)))

def masks_and_sigma(data):
    x = data.x1v[None, None, :]
    y = data.x2v[None, :, None]
    z = z_centers_for(data)[:, None, None]
    t = data.time
    m1, m2 = interp(1, t), interp(2, t)
    x1, y1, z1 = interp(3, t), interp(4, t), interp(5, t)
    x2, y2, z2 = interp(6, t), interp(7, t), interp(8, t)
    chi1, chi2 = interp_vec([9,10,11], t), interp_vec([12,13,14], t)
    a1, a2 = m1*chi1, m2*chi2
    rH1 = m1 + math.sqrt(max(m1*m1 - float(np.dot(a1, a1)), 0.0))
    rH2 = m2 + math.sqrt(max(m2*m2 - float(np.dot(a2, a2)), 0.0))
    r1 = kerr_radius(x-x1, y-y1, z-z1, a1)
    r2 = kerr_radius(x-x2, y-y2, z-z2, a2)
    mask_h = (r1 <= rH1) | (r2 <= rH2)
    dxs = []
    for coords in (data.x1v, data.x2v, z_centers_for(data)):
        if len(coords) > 1:
            dxs.append(float(np.nanmin(np.abs(np.diff(coords)))))
    local_dx = max(dxs) if dxs else 1.0
    auto_sink_radius = 10.0*local_dx
    mask_sink = (np.sqrt((x-x1)**2 + (y-y1)**2 + (z-z1)**2) <= auto_sink_radius) | (
        np.sqrt((x-x2)**2 + (y-y2)**2 + (z-z2)**2) <= auto_sink_radius)
    rho = data.variables['dens']
    b2 = data.variables['bcc1']**2 + data.variables['bcc2']**2 + data.variables['bcc3']**2
    sigma = b2/np.maximum(rho, 1.0e-300)
    return mask_h, mask_sink, sigma

def collect():
    div_rows = []
    sigma_rows = []
    finite_fail = []
    for run, label in zip(runs, labels):
        for path in sorted((run/'bin').glob('torus.mhd_divb.*.bin')):
            d = read_binary_slice(path, ['divb'])
            arr = d.variables['divb']
            if not np.all(np.isfinite(arr)):
                finite_fail.append(str(path))
            div_rows.append([label, d.time/torbit, float(np.nanmax(np.abs(arr))),
                             float(np.sqrt(np.nanmean(arr*arr)))])
        for path in sorted((run/'bin').glob('torus.mhd_w_bcc.*.bin')):
            d = read_binary_slice(path, ['dens','bcc1','bcc2','bcc3'])
            for name, arr in d.variables.items():
                if not np.all(np.isfinite(arr)):
                    finite_fail.append(f'{{path}}:{{name}}')
            mask_h, mask_sink, sigma = masks_and_sigma(d)
            for region, mask in [('horizon', mask_h), ('sink_radius', mask_sink)]:
                vals = sigma[mask]
                sigma_rows.append([label, region, d.time/torbit, vals.size,
                                   float(np.nanmean(vals)) if vals.size else np.nan,
                                   float(np.nanmedian(vals)) if vals.size else np.nan,
                                   float(np.nanmax(vals)) if vals.size else np.nan])
    return np.array(div_rows, dtype=object), np.array(sigma_rows, dtype=object), finite_fail

div_rows, sigma_rows, finite_fail = collect()
case_dir.mkdir(parents=True, exist_ok=True)
np.savetxt(case_dir/'zoom_sink_divb_history.csv', div_rows, fmt='%s', delimiter=',',
           header='stage,orbits,max_abs_divb,rms_divb')
np.savetxt(case_dir/'zoom_sink_sigma_history.csv', sigma_rows, fmt='%s', delimiter=',',
           header='stage,region,orbits,ncells,mean,median,max')

fig, ax = plt.subplots(figsize=(7,4))
for label in labels:
    rows = div_rows[div_rows[:,0] == label]
    if rows.size:
        ax.semilogy(rows[:,1].astype(float), rows[:,2].astype(float), 'o-', label=label)
ax.set_xlabel('time [orbits]')
ax.set_ylabel('max |divB|')
ax.grid(True, alpha=0.3)
ax.legend()
fig.tight_layout()
fig.savefig(case_dir/'zoom_sink_divb_history.png', dpi=160)

fig, ax = plt.subplots(figsize=(7,4))
for label in labels:
    rows = sigma_rows[(sigma_rows[:,0] == label) & (sigma_rows[:,1] == 'sink_radius')]
    if rows.size:
        ax.semilogy(rows[:,2].astype(float), rows[:,4].astype(float), 'o-', label=label)
ax.set_xlabel('time [orbits]')
ax.set_ylabel('mean sigma inside sink radius')
ax.grid(True, alpha=0.3)
ax.legend()
fig.tight_layout()
fig.savefig(case_dir/'zoom_sink_sigma_history.png', dpi=160)

mhd_files = sorted((runs[-1]/'bin').glob('torus.mhd_w_bcc.*.bin'))
if mhd_files:
    last = read_binary_slice(mhd_files[-1], ['dens','bcc1','bcc2','bcc3'])
    zv = z_centers_for(last)
    k0 = int(np.argmin(np.abs(zv)))
    rho = last.variables['dens'][k0]
    b2 = last.variables['bcc1'][k0]**2 + last.variables['bcc2'][k0]**2 + last.variables['bcc3'][k0]**2
    sigma = b2/np.maximum(rho, 1.0e-300)
    np.savez(case_dir/'zoom_sink_xy_slice_final.npz', x=last.x1v, y=last.x2v,
             rho=rho, bcc1=last.variables['bcc1'][k0], bcc2=last.variables['bcc2'][k0],
             bcc3=last.variables['bcc3'][k0], sigma=sigma, time=last.time)
    fig, axs = plt.subplots(1, 3, figsize=(13,4), constrained_layout=True)
    extent = [last.x1v[0], last.x1v[-1], last.x2v[0], last.x2v[-1]]
    for ax, arr, title in zip(axs, [rho, np.sqrt(b2), sigma], ['rho', '|B|', 'sigma']):
        im = ax.imshow(np.log10(np.maximum(arr, 1e-300)), origin='lower',
                       extent=extent, cmap='magma')
        ax.set_title(f'log10 {{title}}, t={{last.time/torbit:.2f}} orbits')
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        fig.colorbar(im, ax=ax, shrink=0.85)
    fig.savefig(case_dir/'zoom_sink_xy_slice_final.png', dpi=180)

if finite_fail:
    raise SystemExit('non-finite diagnostics: ' + '; '.join(finite_fail[:8]))
if div_rows.size and float(np.max(div_rows[:,2].astype(float))) > 1.0e-10:
    raise SystemExit(f'divB exceeded tolerance: {{np.max(div_rows[:,2].astype(float)):.3e}}')

print('divB max', float(np.max(div_rows[:,2].astype(float))) if div_rows.size else float('nan'))
sink_rows = sigma_rows[sigma_rows[:,1] == 'sink_radius']
if sink_rows.size:
    print('sink sigma first/last mean', float(sink_rows[0,4]), float(sink_rows[-1,4]))
print('wrote diagnostics in', case_dir)
"""


def write_diagnostics() -> None:
    DIAG_SCRIPT.write_text(diagnostics_source(), encoding="utf-8")
    cells = [
        nb_cell(
            "# DynBBH Sink-to-AMR Zoom Diagnostics\n"
            "This notebook runs the same diagnostics as "
            "`run_zoom_sink_diagnostics.py`: magnetic divergence, sigma inside "
            "the sink/horizon regions, and a final xy slice.",
            "markdown",
        ),
        nb_cell(diagnostics_source()),
    ]
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    NOTEBOOK.write_text(json.dumps(nb, indent=2), encoding="utf-8")


def main() -> None:
    CASE.mkdir(parents=True, exist_ok=True)
    RUN_LOW.mkdir(parents=True, exist_ok=True)
    RUN_ZOOM.mkdir(parents=True, exist_ok=True)
    write_table()
    write_inputs()
    write_diagnostics()
    print(f"torbit={TORBIT:.16e}")
    print(f"low tlim={LOW_TLIM:.16e}, zoom tlim={ZOOM_TLIM:.16e}")
    print(f"wrote {LOW_INPUT}")
    print(f"wrote {ZOOM_INPUT}")
    print(f"wrote {NOTEBOOK}")
    print(f"wrote {DIAG_SCRIPT}")


if __name__ == "__main__":
    main()
