#!/usr/bin/env python3
"""Run and summarize centered Minkowski-background TOV stability sweeps."""

from __future__ import annotations

import argparse
import math
import re
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RADIUS = 1.15235


@dataclass(frozen=True)
class Case:
    label: str
    nx: int
    half_width: float
    boost: float
    purpose: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--athena", type=Path, default=REPO_ROOT / "build_tov_cpu" / "src" / "athena")
    parser.add_argument("--runner-prefix", default="")
    parser.add_argument("--run-root", type=Path, default=REPO_ROOT / "runs" / "tov_minkowski_stability")
    parser.add_argument("--summary", type=Path, default=REPO_ROOT / "tov_stability.md")
    parser.add_argument("--tlim", type=float, default=2.0)
    parser.add_argument("--hst-dt", type=float, default=0.1)
    parser.add_argument("--wall-time", default="00:20:00")
    parser.add_argument("--moderate-boost", type=float, default=0.2)
    parser.add_argument("--z4c-diss", type=float, default=0.0)
    parser.add_argument("--z4c-kappa1", type=float, default=0.0)
    parser.add_argument("--z4c-kappa2", type=float, default=0.0)
    parser.add_argument(
        "--cases",
        default="unboosted_L3_n32,unboosted_L3_n48,unboosted_L3_n64,"
        "boosted_L3_n32,boosted_L3_n48,boosted_L3_n64,"
        "unboosted_L5_n80,boosted_L5_n80",
        help="Comma-separated case names. Supported names use unboosted/boosted_L<half-width>_n<nx>.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def parse_case(name: str, moderate_boost: float) -> Case:
    match = re.fullmatch(r"(unboosted|boosted)_L([0-9.]+)_n([0-9]+)", name)
    if not match:
        raise ValueError(f"unsupported case name: {name}")
    kind, half_width, nx = match.groups()
    boost = 0.0 if kind == "unboosted" else moderate_boost
    purpose = "boundary" if float(half_width) != 3.0 else "resolution"
    return Case(name, int(nx), float(half_width), boost, purpose)


def input_text(case: Case, tlim: float, hst_dt: float, z4c_diss: float,
               z4c_kappa1: float, z4c_kappa2: float) -> str:
    if case.nx % 16 != 0:
        raise ValueError(f"{case.label}: nx={case.nx} is not divisible by meshblock size 16")
    half_width = case.half_width
    return f"""# Generated by analysis/run_tov_stability.py

<job>
basename = tov_minkowski_{case.label}

<mesh>
nghost = 4
nx1 = {case.nx}
x1min = {-half_width:.16g}
x1max = {half_width:.16g}
ix1_bc = outflow
ox1_bc = outflow

nx2 = {case.nx}
x2min = {-half_width:.16g}
x2max = {half_width:.16g}
ix2_bc = outflow
ox2_bc = outflow

nx3 = {case.nx}
x3min = {-half_width:.16g}
x3max = {half_width:.16g}
ix3_bc = outflow
ox3_bc = outflow

<meshblock>
nx1 = 16
nx2 = 16
nx3 = 16

<time>
evolution = dynamic
integrator = rk2
cfl_number = 0.2
nlim = -1
tlim = {tlim:.16g}
ndiag = 10

<mhd>
evolution = dynamic
eos = ideal
dyn_eos = ideal
dyn_error = reset_floor
reconstruct = wenoz
rsolver = hlle
fofc_method = hlle
gamma = 1.6666666666666667
dfloor = 1.0e-16
pfloor = 1.0e-22
gamma_max = 10.0

<adm>

<coord>
general_rel = true
is_dynamical = true
minkowski = true
a = 0.0
excise = false

<z4c>
use_analytic_background = true
diss = {z4c_diss:.16g}
damp_kappa1 = {z4c_kappa1:.16g}
damp_kappa2 = {z4c_kappa2:.16g}
lapse_harmonic = 0.0
lapse_oplog = 2.0
shift_Gamma = 1.0
shift_eta = 2.0

<problem>
pgen_name = z4c_tov_ks
user_hist = true
bh_mass = 0.0
bh_spin = 0.0
bh_center_x1 = 0.0
bh_center_x2 = 0.0
bh_center_x3 = 0.0
star_center_x1 = 0.0
star_center_x2 = 0.0
star_center_x3 = 0.0
star_boost_x = 0.0
star_boost_y = {case.boost:.16g}
star_boost_z = 0.0
isotropic = true
rhoc = 1.0e-6
kappa = 5.0e-3
npoints = 200000
dr = 2.5e-4
rho_cut = 1.0e-16
excision_damp_rate = 0.0
excision_freeze_radius = 0.0
excision_ramp_radius = 0.0
amr_bh_exclusion_radius = 0.0
b_norm = 0.0

<output1>
file_type = hst
dt = {hst_dt:.16g}
"""


def run_case(athena: Path, runner_prefix: list[str], run_root: Path, case: Case, tlim: float,
             hst_dt: float, z4c_diss: float, z4c_kappa1: float, z4c_kappa2: float,
             wall_time: str, dry_run: bool) -> dict:
    case_dir = run_root / case.label
    case_dir.mkdir(parents=True, exist_ok=True)
    input_path = case_dir / "input.athinput"
    input_path.write_text(input_text(case, tlim, hst_dt, z4c_diss, z4c_kappa1, z4c_kappa2))
    log_path = case_dir / "run.log"
    if dry_run:
        return analyze_case(case_dir, case, returncode=-999, target_time=tlim)

    cmd = runner_prefix + [str(athena), "-i", str(input_path), "-d", str(case_dir), "-t", wall_time]
    with log_path.open("w") as log:
        proc = subprocess.run(cmd, cwd=REPO_ROOT, stdout=log, stderr=subprocess.STDOUT, check=False)
    return analyze_case(case_dir, case, proc.returncode, tlim)


def read_hst(path: Path) -> tuple[list[str], np.ndarray]:
    lines = path.read_text().splitlines()
    header = next(line for line in lines if line.startswith("#  [1]="))
    names = [token.split("]=", 1)[1] for token in header.split() if "]=" in token]
    data = np.loadtxt(path, comments="#", ndmin=2)
    return names, data


def read_history(case_dir: Path, suffix: str) -> tuple[list[str], np.ndarray]:
    files = sorted(case_dir.glob(f"*.{suffix}.hst"))
    if not files:
        return [], np.empty((0, 0))
    return read_hst(files[0])


def parse_radius(log_text: str) -> float:
    match = re.search(r"Radius \(Isotropic\):\s*([0-9.eE+-]+)", log_text)
    return float(match.group(1)) if match else DEFAULT_RADIUS


def relative_slope(time: np.ndarray, values: np.ndarray) -> float:
    if len(time) < 3 or np.nanmean(values) == 0.0:
        return float("nan")
    slope = np.polyfit(time, values, 1)[0]
    return float(slope*(time[-1] - time[0])/np.nanmean(values))


def analyze_case(case_dir: Path, case: Case, returncode: int, target_time: float) -> dict:
    log_text = (case_dir / "run.log").read_text() if (case_dir / "run.log").exists() else ""
    radius = parse_radius(log_text)
    cells_per_radius = radius/(2.0*case.half_width/case.nx)
    cells_across_star = 2.0*cells_per_radius

    user_names, user_hst = read_history(case_dir, "user")
    mhd_names, mhd_hst = read_history(case_dir, "mhd")
    user_idx = {name: i for i, name in enumerate(user_names)}
    mhd_idx = {name: i for i, name in enumerate(mhd_names)}

    final_time = float("nan")
    rho0 = rhof = rho_frac_final = rho_tail_std = rho_tail_slope = float("nan")
    if user_hst.size and "rho-max" in user_idx:
        time = user_hst[:, user_idx["time"]]
        rho = user_hst[:, user_idx["rho-max"]]
        final_time = float(time[-1])
        rho0 = float(rho[0])
        rhof = float(rho[-1])
        rho_frac_final = (rhof - rho0)/rho0 if rho0 != 0.0 else float("nan")
        tail = max(3, len(rho)//3)
        tail_rho = rho[-tail:]
        tail_time = time[-tail:]
        mean_tail = float(np.nanmean(tail_rho))
        rho_tail_std = float(np.nanstd(tail_rho)/mean_tail) if mean_tail != 0.0 else float("nan")
        rho_tail_slope = relative_slope(tail_time, tail_rho)
    elif mhd_hst.size and "time" in mhd_idx:
        final_time = float(mhd_hst[-1, mhd_idx["time"]])

    mass_drift = float("nan")
    if mhd_hst.size and "mass" in mhd_idx:
        mass0 = float(mhd_hst[0, mhd_idx["mass"]])
        massf = float(mhd_hst[-1, mhd_idx["mass"]])
        mass_drift = (massf - mass0)/mass0 if mass0 != 0.0 else float("nan")

    completed = returncode == 0 and np.isfinite(final_time) and final_time >= 0.98*target_time
    settled = (
        completed
        and np.isfinite(rho_tail_std)
        and rho_tail_std < 0.05
        and (not np.isfinite(rho_tail_slope) or abs(rho_tail_slope) < 0.15)
        and np.isfinite(rho_frac_final)
        and abs(rho_frac_final) < 0.5
    )

    return {
        "case": case.label,
        "purpose": case.purpose,
        "nx": case.nx,
        "half_width": case.half_width,
        "boost": case.boost,
        "radius": radius,
        "cells_per_radius": cells_per_radius,
        "cells_across_star": cells_across_star,
        "returncode": returncode,
        "final_time": final_time,
        "mass_drift": mass_drift,
        "rho0": rho0,
        "rhof": rhof,
        "rho_frac_final": rho_frac_final,
        "rho_tail_std": rho_tail_std,
        "rho_tail_slope": rho_tail_slope,
        "settled": settled,
        "dir": case_dir,
    }


def fmt(value: float, digits: int = 3) -> str:
    if not np.isfinite(value):
        return "n/a"
    return f"{value:.{digits}g}"


def write_summary(path: Path, results: list[dict], target_time: float, hst_dt: float,
                  z4c_diss: float, z4c_kappa1: float, z4c_kappa2: float) -> None:
    lines: list[str] = []
    lines.append("# TOV Stability Sweep")
    lines.append("")
    lines.append("Setup: centered TOV star with `bh_mass = 0`, `coord/minkowski = true`, `lapse = 1`, `shift = 0`, `nghost = 4`, `reconstruct = wenoz`, and `rsolver = hlle`.")
    lines.append(f"Z4c parameters: `diss = {z4c_diss:g}`, `damp_kappa1 = {z4c_kappa1:g}`, `damp_kappa2 = {z4c_kappa2:g}`.")
    lines.append(f"The moderate boost is along `+y`. Histories were written every `{hst_dt:g}` and runs targeted `t = {target_time:g}`.")
    lines.append("The stability flag is based on the `rho-max` history: the run must reach the target time, keep the final central-density proxy within 50% of its initial value, and have a final-third fractional scatter below 5% with no strong tail drift.")
    lines.append("")
    lines.append("| case | purpose | L | nx^3 | boost | cells across star | final t | Delta rho_c/rho_c0 | tail std/rho | tail drift | Delta M/M0 | settled |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|")
    for r in results:
        lines.append(
            f"| {r['case']} | {r['purpose']} | {fmt(r['half_width'])} | {r['nx']} | "
            f"{r['boost']:.3g} | {fmt(r['cells_across_star'])} | {fmt(r['final_time'])} | "
            f"{fmt(r['rho_frac_final'])} | {fmt(r['rho_tail_std'])} | "
            f"{fmt(r['rho_tail_slope'])} | {fmt(r['mass_drift'])} | "
            f"{'yes' if r['settled'] else 'no'} |"
        )

    lines.append("")
    for boost_label, boost in [("unboosted", 0.0), ("boosted", None)]:
        subset = [r for r in results if (r["boost"] == 0.0 if boost == 0.0 else r["boost"] != 0.0)]
        settled = [r for r in subset if r["settled"] and r["half_width"] == 3.0]
        if settled:
            best = min(settled, key=lambda r: r["cells_across_star"])
            lines.append(f"- `{boost_label}`: lowest settled centered-box resolution tested was `{best['cells_across_star']:.1f}` cells across the stellar diameter (`nx={best['nx']}`, `L={best['half_width']:g}`).")
        elif subset:
            lines.append(f"- `{boost_label}`: no settled centered-box case was found in this tested range.")
    lines.append("")
    lines.append("Boundary-location check: compare cases with similar points across the star but larger `L`; differences in tail drift or scatter at larger `L` indicate sensitivity to the constraint-violating outer boundary.")
    lines.append("")
    lines.append("Run directories:")
    for r in results:
        lines.append(f"- `{r['case']}`: `{r['dir']}`")
    lines.append("")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    args = parse_args()
    runner_prefix = shlex.split(args.runner_prefix)
    cases = [parse_case(name.strip(), args.moderate_boost)
             for name in args.cases.split(",") if name.strip()]
    args.run_root.mkdir(parents=True, exist_ok=True)

    results = []
    for case in cases:
        print(f"running {case.label}: nx={case.nx}, L={case.half_width}, boost={case.boost}",
              flush=True)
        results.append(run_case(args.athena, runner_prefix, args.run_root, case, args.tlim,
                                args.hst_dt, args.z4c_diss, args.z4c_kappa1,
                                args.z4c_kappa2, args.wall_time, args.dry_run))
    write_summary(args.summary, results, args.tlim, args.hst_dt, args.z4c_diss,
                  args.z4c_kappa1, args.z4c_kappa2)
    print(args.summary)


if __name__ == "__main__":
    main()
