#!/usr/bin/env python3
"""Generate and run 200M TOV stability cases with optional one-level AMR."""

from __future__ import annotations

import argparse
import re
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Case:
    label: str
    half_width: float
    nx: int
    boost: float
    amr: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--athena", type=Path, default=REPO_ROOT / "build_cuda_nompi_z4c_tov_ks" / "src" / "athena")
    parser.add_argument("--runner-prefix", default="")
    parser.add_argument("--run-root", type=Path, required=True)
    parser.add_argument("--tlim", type=float, default=200.0)
    parser.add_argument("--hst-dt", type=float, default=1.0)
    parser.add_argument("--wall-time", default="01:00:00")
    parser.add_argument("--boost", type=float, default=0.2)
    parser.add_argument(
        "--cases",
        default="unboosted_L5_n80,boosted_L5_n80,unboosted_L10_n80_amr1,boosted_L10_n80_amr1",
    )
    return parser.parse_args()


def parse_case(name: str, boost: float) -> Case:
    match = re.fullmatch(r"(unboosted|boosted)_L([0-9.]+)_n([0-9]+)(_amr1)?", name)
    if not match:
        raise ValueError(f"unsupported case: {name}")
    kind, half_width, nx, amr = match.groups()
    return Case(name, float(half_width), int(nx), boost if kind == "boosted" else 0.0, bool(amr))


def input_text(case: Case, tlim: float, hst_dt: float) -> str:
    if case.nx % 16 != 0:
        raise ValueError(f"{case.label}: nx must be divisible by meshblock size 16")
    l = case.half_width
    lines = [f"""# Generated by analysis/run_tov_200m_stability.py

<job>
basename = tov200_{case.label}

<mesh>
nghost = 4
nx1 = {case.nx}
x1min = {-l:.16g}
x1max = {l:.16g}
ix1_bc = outflow
ox1_bc = outflow

nx2 = {case.nx}
x2min = {-l:.16g}
x2max = {l:.16g}
ix2_bc = outflow
ox2_bc = outflow

nx3 = {case.nx}
x3min = {-l:.16g}
x3max = {l:.16g}
ix3_bc = outflow
ox3_bc = outflow

<meshblock>
nx1 = 16
nx2 = 16
nx3 = 16
"""]
    if case.amr:
        lines.append("""
<mesh_refinement>
refinement = adaptive
num_levels = 2
refinement_interval = 2
max_nmb_per_rank = 512

<amr_criterion0>
method = user
""")
    lines.append(f"""
<time>
evolution = dynamic
integrator = rk2
cfl_number = 0.2
nlim = -1
tlim = {tlim:.16g}
ndiag = 10

<mhd>
evolution = dynamic
eos = ideal
dyn_eos = ideal
dyn_error = reset_floor
reconstruct = wenoz
rsolver = hlle
fofc_method = hlle
gamma = 1.6666666666666667
dfloor = 1.0e-16
pfloor = 1.0e-22
gamma_max = 10.0

<adm>

<coord>
general_rel = true
is_dynamical = true
minkowski = true
a = 0.0
excise = false

<z4c>
use_analytic_background = true
diss = 0.5
damp_kappa1 = 0.0
damp_kappa2 = 0.0
lapse_harmonic = 0.0
lapse_oplog = 2.0
shift_Gamma = 1.0
shift_eta = 2.0

<problem>
pgen_name = z4c_tov_ks
user_hist = true
bh_mass = 0.0
bh_spin = 0.0
bh_center_x1 = 0.0
bh_center_x2 = 0.0
bh_center_x3 = 0.0
star_center_x1 = 0.0
star_center_x2 = 0.0
star_center_x3 = 0.0
star_boost_x = 0.0
star_boost_y = {case.boost:.16g}
star_boost_z = 0.0
isotropic = true
rhoc = 1.0e-6
kappa = 5.0e-3
npoints = 200000
dr = 2.5e-4
rho_cut = 1.0e-16
excision_damp_rate = 0.0
excision_freeze_radius = 0.0
excision_ramp_radius = 0.0
amr_bh_exclusion_radius = 0.0
amr_rho_slope_threshold = 0.25
amr_rho_min = 1.0e-12
amr_star_refine = {'true' if case.amr else 'false'}
amr_star_refine_radius = 1.5
amr_star_refine_level = 1
b_norm = 0.0

<output1>
file_type = hst
dt = {hst_dt:.16g}
""")
    return "".join(lines)


def run_case(args: argparse.Namespace, case: Case, runner: list[str]) -> None:
    case_dir = args.run_root / case.label
    case_dir.mkdir(parents=True, exist_ok=True)
    input_path = case_dir / "input.athinput"
    input_path.write_text(input_text(case, args.tlim, args.hst_dt))
    cmd = runner + [str(args.athena), "-i", str(input_path), "-d", str(case_dir), "-t", args.wall_time]
    with (case_dir / "run.log").open("w") as log:
        proc = subprocess.run(cmd, cwd=REPO_ROOT, stdout=log, stderr=subprocess.STDOUT, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"{case.label} failed with return code {proc.returncode}")


def main() -> None:
    args = parse_args()
    args.run_root.mkdir(parents=True, exist_ok=True)
    runner = shlex.split(args.runner_prefix)
    cases = [parse_case(name.strip(), args.boost) for name in args.cases.split(",") if name.strip()]
    for case in cases:
        print(f"running {case.label}: L={case.half_width}, nx={case.nx}, boost={case.boost}, amr={case.amr}", flush=True)
        run_case(args, case, runner)
    print(args.run_root)


if __name__ == "__main__":
    main()
